In [1]:
import numpy as np

**References (pointers)**

In [2]:
a = np.array([1,2,3])
b = a
c = a[1:] # slicing
b[0] = 3 # indexing
c[0] = 3
print(a)

[3 3 3]


**Types and in-place operations:**

In [3]:
x = np.array([1,2,3])
y = x
x += 1
x[:] = x + 1
x = x + 1
print(x)

[4 5 6]


**Functions and scope:**

In [4]:
a = 1
def f(x):
	return x+a
print(f(1))
a = 2
print(f(1))

2
3


**Computational tree and branches**

In [5]:
x0 = 1
n = 4
evaluate = lambda x: 0.5*x
check = lambda y: y < 0.10
update = lambda x,y: y

x = x0
for i in range(n):
    y = evaluate(x)
    if check(y): break
    x = update(x,y)
else:
    raise ValueError('did not converge')

In [6]:
x = x0
i = 0
while True:
    y = evaluate(x)
    if check(y): break
    x = update(x,y)
    i += 1
    if i >= n:
        raise ValueError('did not converge')

**Decimal numbers are not exact**

In [7]:
print(0.1 + 0.2 == 0.3)
print(0.5 + 0.5 == 1.0)
print(np.isclose(0.1+0.2,0.3))
print(np.isclose(1e-200*1e200*1e200*1e-200,1.0))
print(np.isinf(1e-200*(1e200*1e200)*1e-200))
print(np.isclose(1e200*(1e-200*1e-200)*1e200,0.0))

False
True
True
True
True
True


**Random numers:**

In [8]:
rng = np.random.default_rng(123)
s = rng.bit_generator.state
x = rng.normal(size=5)
y = rng.normal(size=5)
rng.bit_generator.state = s
z = rng.normal(size=5)
print(x)
print(y)
print(z)

[-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]
[ 0.57710379 -0.63646365  0.54195222 -0.31659545 -0.32238912]
[-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]


Old style:

In [9]:
np.random.seed(123)
s = np.random.get_state()
x = np.random.normal(size=5)
y = np.random.normal(size=5)
np.random.set_state(s)
z = np.random.normal(size=5)
print(x)    
print(y)
print(z)

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
[ 1.65143654 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
